### Load Libraries

In [12]:
#load pandas, numpy

import pandas as pd
import numpy as np

### Import campus dataset

In [13]:
campus = pd.read_csv('/kaggle/input/salesforce-dataset-project/Salesforce_data_case_study.csv')

## Explore Data

In [14]:
campus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12920 entries, 0 to 12919
Data columns (total 40 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   person_id                                 12920 non-null  int64
 1   gender                                    12920 non-null  object
 2   age                                       12920 non-null  int64
 3   race                                      12920 non-null  object
 4   hispanic?                                 12920 non-null  object
 5   high_school_grad?                         12920 non-null  object
 6   ged_received?                             12920 non-null  object
 7   first_gen_college?                        12920 non-null  object
 8   past_college_enrollment                   12920 non-null  object
 9   zipcode                                   12920 non-null  object
 10  city                                      12920 non-null  object
 11  state                                     12799 non-null  object
 12  veteran_status                            12920 non-null  object
 13  lead_created_date                         12916 non-null  object
 14  hear_about_campus                         12920 non-null  object
 15  utm_marketing_channel                     12920 non-null  object
 16  application_start_date                    12920 non-null  object
 17  first_meaningful_conversation_date        2965 non-null   object
 18  application_submit_date                   12906 non-null  object
 19  interview_date                            1954 non-null   object
 20  async_interview_date_c                    285 non-null    object
 21  assessment_decision                       12920 non-null  object
 22  assessment_attempts                       12920 non-null  int64
 23  admit_date                                1882 non-null   object
 24  admit_status                              1879 non-null   object
 25  enroll_date                               911 non-null    object
 26  was_previous_enrollment                   12920 non-null  bool
 27  num_phone_calls                           12920 non-null  int64
 28  offer_letter_status                       12920 non-null  object
 29  offer_letter_status_date                  1102 non-null   object
 30  fafsa_status                              12920 non-null  object
 31  enrollment_identity_verification_status   12920 non-null  object
 32  highschool_grad_verification_status       12920 non-null  object
 33  Registration Status end of first term     911 non-null    object
 34  Credits Completed end of first term       911 non-null    float64
 35  Credits attempted in students first term  911 non-null    float64
 36  GPA end of First Term                     501 non-null    float64
 37  last_date_attendance                      755 non-null    object
 38  quarter_start_date                        12920 non-null  object
 39  quarter_end_date                          12920 non-null  object
dtypes: bool(1), float64(3), int64(4), object(32)
memory usage: 3.9+ MB

### Transform Data

In [15]:
# shorten/simplfy column names

In [16]:

campus = campus.rename(columns={
    'application_start_date': 'date_app_start',
    'offer_letter_status': 'status_offer_letter',
    'utm_marketing_channel': 'utm_marketing', 
    'last_date_attendance': 'date_last_attend',
    'offer_letter_status_date':'date_offer_letter',
    'application_submit_date':'date_app_submit',
    'interview_date': 'date_interview',
    'async_interview_date_c':'date_async',
    'admit_date':'date_admit',
    'enroll_date':'date_enroll',
    'quarter_start_date':'date_qtr_start',
    'quarter_end_date':'date_qtr_end',
    'lead_created_date': 'date_lead',
    'first_meaningful_conversation_date': 'date_first_convo',
    'admit_status': 'status_admit',
    'offer_letter_status':'status_offer_letter'
})

In [17]:
campus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12920 entries, 0 to 12919
Data columns (total 40 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   person_id                                 12920 non-null  int64
 1   gender                                    12920 non-null  object
 2   age                                       12920 non-null  int64
 3   race                                      12920 non-null  object
 4   hispanic?                                 12920 non-null  object
 5   high_school_grad?                         12920 non-null  object
 6   ged_received?                             12920 non-null  object
 7   first_gen_college?                        12920 non-null  object
 8   past_college_enrollment                   12920 non-null  object
 9   zipcode                                   12920 non-null  object
 10  city                                      12920 non-null  object
 11  state                                     12799 non-null  object
 12  veteran_status                            12920 non-null  object
 13  date_lead                                 12916 non-null  object
 14  hear_about_campus                         12920 non-null  object
 15  utm_marketing                             12920 non-null  object
 16  date_app_start                            12920 non-null  object
 17  date_first_convo                          2965 non-null   object
 18  date_app_submit                           12906 non-null  object
 19  date_interview                            1954 non-null   object
 20  date_async                                285 non-null    object
 21  assessment_decision                       12920 non-null  object
 22  assessment_attempts                       12920 non-null  int64
 23  date_admit                                1882 non-null   object
 24  status_admit                              1879 non-null   object
 25  date_enroll                               911 non-null    object
 26  was_previous_enrollment                   12920 non-null  bool
 27  num_phone_calls                           12920 non-null  int64
 28  status_offer_letter                       12920 non-null  object
 29  date_offer_letter                         1102 non-null   object
 30  fafsa_status                              12920 non-null  object
 31  enrollment_identity_verification_status   12920 non-null  object
 32  highschool_grad_verification_status       12920 non-null  object
 33  Registration Status end of first term     911 non-null    object
 34  Credits Completed end of first term       911 non-null    float64
 35  Credits attempted in students first term  911 non-null    float64
 36  GPA end of First Term                     501 non-null    float64
 37  date_last_attend                          755 non-null    object
 38  date_qtr_start                            12920 non-null  object
 39  date_qtr_end                              12920 non-null  object
dtypes: bool(1), float64(3), int64(4), object(32)
memory usage: 3.9+ MB

In [19]:
date_funnel = [
    'date_offer_letter', 'date_last_attend', 'date_qtr_start', 
    'date_qtr_end', 'date_enroll', 'date_admit', 'date_lead',
    'date_app_start', 'date_first_convo', 'date_interview',
    'date_app_submit', 'date_async', 'status_admit', 'status_offer_letter'
]

campus_funnel = campus[date_funnel]

In [18]:
campus_funnel = campus[date_funnel]

In [20]:
print(campus_funnel)

      date_offer_letter date_last_attend date_qtr_start date_qtr_end  \
0                   NaN              NaN     2024-10-07   2024-12-12
1                   NaN              NaN     2024-10-07   2024-12-12
2                   NaN              NaN     2024-10-07   2024-12-12
3                   NaN              NaN     2024-10-07   2024-12-12
4                   NaN              NaN     2024-10-07   2024-12-12
...                 ...              ...            ...          ...
12915        2024-09-17       2024-11-07     2024-10-07   2024-12-12
12916        2024-07-24       2024-12-10     2024-10-07   2024-12-12
12917        2024-08-12              NaN     2024-10-07   2024-12-12
12918        2024-08-02       2024-11-13     2024-10-07   2024-12-12
12919        2024-09-27       2024-12-12     2024-10-07   2024-12-12

      date_enroll  date_admit   date_lead date_app_start date_first_convo  \
0             NaN         NaN  2024-06-15     2024-06-15              NaN
1             NaN         NaN  2024-06-15     2024-06-15              NaN
2             NaN         NaN  2024-06-15     2024-06-15              NaN
3             NaN         NaN  2024-06-15     2024-06-15              NaN
4             NaN         NaN  2024-06-15     2024-06-15              NaN
...           ...         ...         ...            ...              ...
12915  2024-09-17  2024-09-11  2024-09-10     2024-09-10       2024-09-11
12916  2024-07-24  2024-07-24  2024-07-09     2024-07-10       2024-07-22
12917  2024-08-12  2024-08-08  2024-08-08     2024-08-08       2024-08-13
12918  2024-08-05  2024-08-02  2024-07-30     2024-07-30       2024-08-01
12919  2024-08-13  2024-07-16  2024-07-08     2024-07-08       2024-07-11

      date_interview date_app_submit  date_async            status_admit  \
0                NaN             NaN         NaN                     NaN
1                NaN      2024-06-15         NaN                     NaN
2                NaN      2024-06-15         NaN                     NaN
3                NaN      2024-06-15         NaN                     NaN
4                NaN      2024-06-15         NaN                     NaN
...              ...             ...         ...                     ...
12915     2024-09-11      2024-09-10         NaN  Assessment + Interview
12916     2024-07-22      2024-07-10         NaN  Assessment + Interview
12917            NaN      2024-08-08  2024-08-08            No Interview
12918     2024-08-01      2024-07-30         NaN  Assessment + Interview
12919     2024-07-11      2024-07-08         NaN  Assessment + Interview

      status_offer_letter
0                not sent
1                not sent
2                not sent
3                not sent
4                not sent
...                   ...
12915            complete
12916            complete
12917            complete
12918            complete
12919            complete

[12920 rows x 14 columns]

 ### Create 2 datasets

In [21]:
# 2 separate df - one where status_offer_letter has value, and one without.


campus_with_offer = campus_funnel[campus_funnel['status_offer_letter'].notna()]


campus_empty_offer = campus_funnel[campus_funnel['status_offer_letter'].isna()]

In [23]:
# Save to csv

campus_with_offer.to_csv('campus_with_offer.csv', index = False) 
campus_empty_offer.to_csv('campus_empty_offer.csv', index = False)